CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	name TEXT NOT NULL,
	email TEXT NOT NULL UNIQUE,
	password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS links (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	code VARCHAR(16) NOT NULL UNIQUE,
	original_url TEXT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS analytics (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	link_id UUID NOT NULL UNIQUE REFERENCES links(id) ON DELETE CASCADE,
	clicks BIGINT NOT NULL DEFAULT 0
);
